# Autogenerated by devscripts/update-version.py

__version__ = '2026.08.17.073947'

RELEASE_GIT_HEAD = 'f1896c57f5ba4b92741bb509790837d6838ec99e'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2026.08.17.073947dev'
